name: PlayerLog
version: 1.1.0
api: [1.6.0]
author: yf001
description: プレーヤーのログをとります
main: PlayerLog\MainClass
load: STARTUP

commands:
  log:
    description: "ブロックのログを見ます"
    usage: "/log"
    permission: "log.command.log"
  plog:
    description: "プレーヤーの入退室ログを見ます"
    usage: "/plog　<プレーヤー名> [ページ番号]"
    permission: "log.command.plog"
  rollback:
    description: "指定した範囲をロールバックします"
    usage: "/rollback help"
    permission: "log.command.rollback"
permissions:
  log:
    default: op
    description: "PlayerLogの最高権限"
    children:
      log.command:
        default: op
        description: "PlayerLogのすべてのコマンドを使用できます"
        children:
         log.command.log:
            default: op
            description: "logコマンドを使用できるようになります"
         log.command.rollback:
            default: op
            description: "rollbackコマンドを使用できるようになります"
         log.command.plog:
            default: op
            description: "plogコマンドを使用できるようになります"