#PlayerLogの設定ファイル
# true/有効 false/無効

#データの保存形式 未実装
#対応保存形式 sqlite
provider: sqlite

#ブロックの破壊を記録する
blockbreak: true

#ブロックの設置を記録する
blockplace: true

#プレーヤーがコマンドを打つとコンソールに表示するようにする
playercmd: true

#プレーヤーの入退室を記録する
playerjoin: false

#ブロック名を日本語表示にするか
blockNameJP: true

#時間表示でのGMT(グリニッジ標準時)とのズレ修正(日本時間 +9時間)
GMT: 9